name: moaazapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.0
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images_buttons/
  fonts:
    - family: Source Sans 3
      fonts:
        - asset: assets/fonts/SourceSans3-Regular.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf  
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf  
    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf            
        
